### ISSUE TITLE
Persist state across switch away/back

### ISSUE THREAD

**Issue by chadwhitacre** [zacwood9/Attics#1]
## Steps to Reproduce

1. Listen to some sweet, sweet Grateful Dead tunes on Attics!
2. Stop listening to those sweet, sweet tunes.
3. Return to Attics.

## Expected Result

Pick up where I left off! 🎶 

## Actual Result

Back at the homepage staring at 1965. 😩

## Notes

Seems to be the case even when I leave the app open in the background (don't hard-close it).

**Comment by zacwood9** [comment]
Hey! Thanks for reporting this. This would be a great feature to have and I'll definitely include it in the next release! Hopefully I'll have it up this weekend.

**Comment by chadwhitacre** [comment]
Nice! Let me know if I can help test it out or whatevs, not sure how that works with an iOS project but could be fun to learn. :)

Thanks for Attics! 💃

**Comment by zacwood9** [comment]
Awesome! Before new versions are released on the App Store, they go to TestFlight for a day or two for beta testing. Once v1.1 is on TestFlight, I'll make the invite link public and put it in the README. So if you wanna help test you can download TestFlight and I'll let you know when the beta is up!

**Comment by chadwhitacre** [comment]
Nice! I will try to give that a shot once the link is up. 👍

**Comment by zacwood9** [comment]
The new beta is up! Check the README for instructions on signing up.

Feel free to let me know if you have any other feature requests! Thanks for using Attics.

**Comment by chadwhitacre** [comment]
@zacwood9 This is awesome, thank you! I installed TestFlight and was then able to install the beta version of Attics. Now if I start playing a song and then close the app (double-tap home and swipe up), then reopen, it _does_ take me back to the concert I was last listening to. This is a big improvement! 🎶

What would be even better would be if it took me back to the same song and even the same location within a song as when I last left off. :o) Is this possible?

**Comment by zacwood9** [comment]
Ha, yeah that would be possible :) I'm gonna release this version to the app store though and then put that on the list for future features!

**Comment by chadwhitacre** [comment]
> I'm gonna release this version to the app store

Release early, release often ... I like it! ☺️

> put that on the list for future features

Reticketed as #2. 👍
