### ISSUE TITLE
Add "Getting Started" instructions in the README

### ISSUE THREAD

**Issue by zacwood9** [zacwood9/Attics#11]
Useful to new contributors. Let's try to be professionals 😉

**Comment by deannathompson** [comment]
hi, new to github here and looking to contribute to a few projects. are you looking for someone to write instructions on how to download the app, or is there more to it?

**Comment by zacwood9** [comment]
Hey! It would be nice to have instructions for

1. cloning the repo
2. building the dependencies with Carthage
3. running the app in Xcode

1 and 3 are pretty straightforward but not many apps use Carthage to manage dependencies, so that's probably what would confuse people the most. Let me know if you have any other questions!
